tunnel: 8657036f-19bd-4e43-b286-536f448c6987
credentials-file: /home/sai/.cloudflared/8657036f-19bd-4e43-b286-536f448c6987.json
ingress:
  - hostname: aimlab-api.saibot.site
    service: http://127.0.0.1:5182
  - hostname: aimlab-staging-api.saibot.site
    service: http://127.0.0.1:5282
  - hostname: aimlab-analytics.saibot.site
    path: ^/(script\.js|api/send)$
    service: http://127.0.0.1:5181
  - service: http_status:404
